projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - graphql/**.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/types.ts
        docsFilePath: graphql
        region: us-east-1
        apiId: tx5co4ljbraqpeum4dl5vwnrym
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
